//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro
    {
        public int maestroId { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string identificacion { get; set; }
        public string genero { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<int> direccionFk { get; set; }
        public string contacto { get; set; }
        public string correo { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    
        public virtual Direccion Direccion { get; set; }
    }
}
