//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int matriculaId { get; set; }
        public Nullable<int> alumnoFk { get; set; }
        public Nullable<int> gradoFk { get; set; }
        public Nullable<int> seccionFk { get; set; }
        public string nombreMatricula { get; set; }
        public Nullable<System.DateTime> fechaRegistroMatricula { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Grado Grado { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
