//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int notaid { get; set; }
        public Nullable<int> periodo { get; set; }
        public Nullable<decimal> nota { get; set; }
        public Nullable<int> materiaid_fk { get; set; }
        public Nullable<int> alumnoid_fk { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Materias Materias { get; set; }
    }
}
